[package]
name = "custom_background"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12"
winit = "0.26"
glam = "0.20"
env_logger = "0.9"
pollster = "0.2"
